TRAINING_DATA_PATH = 'data/training_data.csv'
SMALL_TRAINING_DATA_PATH = 'data/small_data.csv'
PROCESSED_DATA_PATH = 'data/processed_data.csv'
VALIDATION_DATA_PATH = 'data/validation_data_processed.csv'
ADDITIONAL_VALIDATION_DATA_PATH = 'data/validation_additional_processed_data.csv'
